name: Test Archctl

on:
  pull_request:
    branches: [main]

jobs:

  Tests:
    runs-on: ubuntu-latest # ${{ matrix.os }}
    
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     os: [ubuntu-latest, macos-latest, windows-latest]
    #     python: ["3.7", "3.8", "3.9", "3.10"]

    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.10 # ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -e .
          if [ -f test_requirements.txt ]; then pip install -r test_requirements.txt; fi

      - name: Lint with flake8
        run: |
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --max-complexity=10 --max-line-length=127 --statistics \
                    --output-file=flake8.txt -extend-ignore W605

      - name: Test with pytest
        run: |
          pytest . --cov=archctl --cov-report=xml --junitxml=xunit-reports/test-results.xml
      
      - name: Fix code coverage paths
        run: |
          sed -i 's/\/home\/runner\/work\/archctl\/archctl\//\/github\/workspace\//g' coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}